feat(contracts): update `OPSuccinctFaultDisputeGame` (#394)
* feat(contracts): use anchor state registry for the first game

* feat(contracts): remove parent game type check

* feat(contracts): check isGameBlacklisted and isGameRespected for create

* feat(contracts): airgap + anchor state + refund

* feat(contracts): add fast finality mode

* feat(contracts): support permissioned proposers and challengers

* cleanup

* cleanup

* ci: install stable version for foundry

Fixes below error
```
Error: failed to resolve file: "/home/runner/work/op-succinct/op
-succinct/contracts/lib/lib-keccak/contracts/lib/LibKeccak.sol":
No such file or directory (os error 2); check configured remappings
	--> /home/runner/work/op-succinct/op-succinct/contracts/lib/
optimism/packages/contracts-bedrock/interfaces/cannon/
IPreimageOracle.sol
	@lib-keccak/LibKeccak.sol
```

* chore: add missing dep

* fix(contracts): fix `extraData()`

* feat: revert fast finality mode

* apply comments

* fix